---
title: "Week 9 Factors HW"
author: "Annie Deck"
date: "2024-11-01"
output: 
 html_document:
  toc: true
  toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message=FALSE,
                      warning=FALSE)
```
# Load libraries 
```{r}
library(here)
library(tidyverse)
library(tidytext)
library(janitor)

```


#Read in data
```{r}
intertidal_data<- read.csv(here("Week_09", "Data", "intertidaldata.csv"))

glimpse(intertidal_data)

```
# Some cleaning needed...
```{r}
##First taking a look at the Qudrat column 
##Looks like we have lots of spaces, numbers, and periods to remove
unique(intertidal_data$Quadrat)

##Using tidytext & janitor
Cleaned_intertidal <- intertidal_data %>%
  clean_names() %>% ##janitor to fix all of the periods and make names consistent
  mutate(quadrat = str_replace_all(quadrat,  "[[:punct:]]|[[:space:]]|[[:digit:]]", "")) ##mutate to edit the quadrat column (now lowercase from janitor)

##checking to see if that worked- looks good!
unique(Cleaned_intertidal$quadrat)
glimpse(Cleaned_intertidal)

##Pivot data longer & grab data I want
Intertidal_data_final <- Cleaned_intertidal %>%
  pivot_longer(cols = c(bare_rock: anemone),  #select column names
               names_to = "Cover", ##put all categories into a column called "Cover"
               values_to = "Percent") %>% ##put all values into a column called "Percent"
  select(c(site, transect, quadrat, Cover, Percent)) %>%  #select columns I want to keep
  filter(site %in% c("Scripps", "Cambria")) %>% ##keep only these two sites to compare
  mutate(quadrat = factor(quadrat)) %>%    ##turn quadrat into a factor 
  droplevels()                              ##drops extra levels

##look at data- looks much better!
glimpse(Intertidal_data_final)

##check order of quadrat levels- alphabetical so needs to be fixed
Intertidal_data_final$quadrat

Intertidal_data_final$quadrat <- factor(Intertidal_data_final$quadrat, levels = c("Low", "Mid", "High"))

##fixed!
Intertidal_data_final$quadrat

```
# Plot!
```{r, fig.align='center', fig.height=9}
##Make a nice color palette
palette5 <- c("#2E8B57", "#4682B4", "#CD853F")

Intertidal_plot <- Intertidal_data_final %>%
  ggplot(aes(x=Cover,
             y= Percent,
             fill= quadrat)) +
  geom_bar(stat = "identity", position = "dodge") +
  facet_wrap(~site, ncol = 1) + ##facet to compare the two sites, stack them vertically
  scale_fill_manual(values = palette5) + ##fill bars with my color palette 
  theme_bw() + ##add a nice theme to get rid of grey background
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + ##rotate x-axis labels to make it less crowded
  labs(title = "Percent Cover by Quadrat at Scripps vs Cambria",
       x = "Cover Type",
       y = "Percent Cover",
       fill = "Quadrat") + ##fix axis labels, legend label, and add title
  scale_x_discrete(
    labels = c("algae" = "Algae", ##fix names of cover categories
               "anemone" = "Anemone",
               "bare_rock" = "Bare Rock",
               "gooseneck_barnacles" = "Gooseneck Barnacles",
               "large_barnacles" = "Large Barnacles",
               "mussels" = "Mussels",
               "small_barnacles" = "Small Barnacles"))  # New x axis labels

Intertidal_plot

##saving
ggsave(here("Week_09", "Output", "Intertidal_plot.png"), width = 10, height = 12)

```

