---
title: "Tidy Tuesday- Monsters"
author: "Annie Deck"
date: "2024-11-11"
output: 
 github_document:
  toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message=FALSE,
                      warning=FALSE)
```

# Load libraries
```{r}
library(tidyverse)
library(here)
library(wordcloud2)
library(tidytext)
```

# Bring in data
## Monster Movies 
```{r}
##read directly from GitHub
monster_movie_genres <-readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-10-29/monster_movie_genres.csv')

monster_movies <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-10-29/monster_movies.csv')

##Take a look at the data
glimpse(monster_movies)

##Save to data folder 
readr::write_csv(monster_movies, here::here("Tidy_Tuesday", "Monsters", "Data", "monster_movies.csv"))

```

# Prepping and cleaning data
```{r}
##remove punctuation from primary titles
monster_movies_clean <- monster_movies %>%
  select(primary_title) %>%
  mutate(primary_title = str_replace_all(primary_title, "[[:punct:]]", " "))

##create word counts
word_counts <- monster_movies_clean %>%
  unnest_tokens(word, primary_title) %>% #break down into individual words
  anti_join(stop_words) %>%   #Remove stop words
  count(word, sort = TRUE) %>% #Count word frequencies
  filter(n >= 2) # Only keep words that appear at least twice

```
# Making word cloud 
```{r}
#make word cloud
wordcloud2(word_counts,
          size = 1,
          color = "random-dark",
          backgroundColor = "black",
          rotateRatio = 0.3,
          shape = "circle")

##"monster" and "monsters" seems very dominant where I can not easily see the other words
##in an attempt to improve this I am going to cap maximum frequency at 20 
word_counts <- monster_movies %>%
  select(primary_title) %>%
  mutate(primary_title = str_replace_all(primary_title, "[[:punct:]]", " ")) %>%
  unnest_tokens(word, primary_title) %>%
  anti_join(stop_words) %>%
  count(word, sort = TRUE) %>%
  mutate(n = if_else(n > 20, 20, n)) %>%  #cap frequency at 20
  filter(n >= 2)

##trying world cloud again with a few modifications- looks better!
monster_wordcloud <-wordcloud2(word_counts,
          size = 0.5,
          color = "random-dark",
          backgroundColor = "black",
          rotateRatio = 0.5,
          minSize = 0.1,
          shape = "circle")

##saving
saveWidget(monster_wordcloud, here("Tidy_Tuesday", "Monsters", "Output", "monster_wordcloud.html"))

```

